version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=e_wallet_system
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - HOST=localhost
      - APP_URL=http://localhost:3000
      - NODE_ENV=development
      - DB_NAME=e_wallet_system
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=3306
    env_file:
      - api.env
    networks:
      - app-network

volumes:
  db-data:
networks:
  app-network:
    driver: bridge
