services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - app-network

  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_URL=${APP_URL}
      - PORT=${PORT}
      - HOST=${HOST}

      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      - TEST_DB_HOST=db
      - TEST_DB_PORT=3306
      - TEST_DB_NAME=${TEST_DB_NAME}
      - TEST_DB_USER=${TEST_DB_USER}
      - TEST_DB_PASSWORD=${TEST_DB_PASSWORD}

      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - FLUTTERWAVE_KEY=${FLUTTERWAVE_KEY}
    networks:
      - app-network

volumes:
  db-data:
networks:
  app-network:
    driver: bridge
